import { Pasien } from '@/types/pasien'

let dummyData: Pasien[] = [
  {
    id: '1',
    nama: 'Jane Doe',
    namaPanggilan: 'Jane',
    tanggalLahir: '2000-01-01',
    gender: 'Perempuan',
    alamat: 'Jl ABC No.1',
    agama: 'Islam',
    pekerjaan: 'Guru',
    status: 'Active',
  },
  {
    id: '2',
    nama: 'Edwin Doe',
    namaPanggilan: 'Uwin',
    tanggalLahir: '1998-01-01',
    gender: 'Laki Laki',
    alamat: 'Jl Aasd No.2',
    agama: 'Islam',
    pekerjaan: 'Tukang',
    status: 'Inactive',
  },
  {
    id: '3',
    nama: 'Rina Marlina',
    namaPanggilan: 'Rina',
    tanggalLahir: '1995-05-12',
    gender: 'Perempuan',
    alamat: 'Jl Merdeka No.3',
    agama: 'Kristen',
    pekerjaan: 'Dokter',
    status: 'Active',
  },
  {
    id: '4',
    nama: 'Budi Santoso',
    namaPanggilan: 'Budi',
    tanggalLahir: '1989-03-21',
    gender: 'Laki Laki',
    alamat: 'Jl Sudirman No.4',
    agama: 'Islam',
    pekerjaan: 'Petani',
    status: 'Active',
  },
  {
    id: '5',
    nama: 'Maya Sari',
    namaPanggilan: 'Maya',
    tanggalLahir: '1993-07-08',
    gender: 'Perempuan',
    alamat: 'Jl Mawar No.5',
    agama: 'Hindu',
    pekerjaan: 'Perawat',
    status: 'Inactive',
  },
  {
    id: '6',
    nama: 'Andi Wijaya',
    namaPanggilan: 'Andi',
    tanggalLahir: '1990-11-30',
    gender: 'Laki Laki',
    alamat: 'Jl Kenanga No.6',
    agama: 'Budha',
    pekerjaan: 'Sopir',
    status: 'Active',
  },
  {
    id: '7',
    nama: 'Sinta Dewi',
    namaPanggilan: 'Sinta',
    tanggalLahir: '2002-09-19',
    gender: 'Perempuan',
    alamat: 'Jl Flamboyan No.7',
    agama: 'Islam',
    pekerjaan: 'Mahasiswa',
    status: 'Inactive',
  },
  {
    id: '8',
    nama: 'Teguh Prasetyo',
    namaPanggilan: 'Teguh',
    tanggalLahir: '1985-06-14',
    gender: 'Laki Laki',
    alamat: 'Jl Melati No.8',
    agama: 'Kristen',
    pekerjaan: 'Satpam',
    status: 'Active',
  },
  {
    id: '9',
    nama: 'Indah Permata',
    namaPanggilan: 'Indah',
    tanggalLahir: '1999-02-22',
    gender: 'Perempuan',
    alamat: 'Jl Anggrek No.9',
    agama: 'Islam',
    pekerjaan: 'Penulis',
    status: 'Active',
  },
  {
    id: '10',
    nama: 'Dedi Supriyadi',
    namaPanggilan: 'Dedi',
    tanggalLahir: '1992-04-04',
    gender: 'Laki Laki',
    alamat: 'Jl Sakura No.10',
    agama: 'Islam',
    pekerjaan: 'Kuli Bangunan',
    status: 'Inactive',
  },
  {
    id: '11',
    nama: 'Wulan Puspita',
    namaPanggilan: 'Wulan',
    tanggalLahir: '2001-08-11',
    gender: 'Perempuan',
    alamat: 'Jl Cemara No.11',
    agama: 'Kristen',
    pekerjaan: 'Freelancer',
    status: 'Active',
  },
  {
    id: '12',
    nama: 'Bayu Hidayat',
    namaPanggilan: 'Bayu',
    tanggalLahir: '1996-12-03',
    gender: 'Laki Laki',
    alamat: 'Jl Teratai No.12',
    agama: 'Islam',
    pekerjaan: 'Desainer',
    status: 'Active',
  },
  {
    id: '13',
    nama: 'Nina Kartika',
    namaPanggilan: 'Nina',
    tanggalLahir: '1997-01-16',
    gender: 'Perempuan',
    alamat: 'Jl Bougenville No.13',
    agama: 'Katolik',
    pekerjaan: 'Kasir',
    status: 'Inactive',
  },
  {
    id: '14',
    nama: 'Hendra Saputra',
    namaPanggilan: 'Hendra',
    tanggalLahir: '1987-10-05',
    gender: 'Laki Laki',
    alamat: 'Jl Cemara No.14',
    agama: 'Islam',
    pekerjaan: 'Montir',
    status: 'Active',
  },
  {
    id: '15',
    nama: 'Ayu Lestari',
    namaPanggilan: 'Ayu',
    tanggalLahir: '2003-03-28',
    gender: 'Perempuan',
    alamat: 'Jl Bambu No.15',
    agama: 'Hindu',
    pekerjaan: 'Pelajar',
    status: 'Active',
  },
  {
    id: '16',
    nama: 'Rangga Saputra',
    namaPanggilan: 'Rangga',
    tanggalLahir: '1994-09-01',
    gender: 'Laki Laki',
    alamat: 'Jl Jati No.16',
    agama: 'Islam',
    pekerjaan: 'Security',
    status: 'Inactive',
  },
  {
    id: '17',
    nama: 'Melati Anjani',
    namaPanggilan: 'Melati',
    tanggalLahir: '2000-05-09',
    gender: 'Perempuan',
    alamat: 'Jl Mahoni No.17',
    agama: 'Islam',
    pekerjaan: 'Asisten Rumah Tangga',
    status: 'Active',
  },
  {
    id: '18',
    nama: 'Fajar Prasetya',
    namaPanggilan: 'Fajar',
    tanggalLahir: '1991-07-07',
    gender: 'Laki Laki',
    alamat: 'Jl Salak No.18',
    agama: 'Kristen',
    pekerjaan: 'Nelayan',
    status: 'Inactive',
  },
  {
    id: '19',
    nama: 'Putri Amalia',
    namaPanggilan: 'Putri',
    tanggalLahir: '1998-10-30',
    gender: 'Perempuan',
    alamat: 'Jl Pisang No.19',
    agama: 'Islam',
    pekerjaan: 'Penjahit',
    status: 'Active',
  },
  {
    id: '20',
    nama: 'Ahmad Zaki',
    namaPanggilan: 'Zaki',
    tanggalLahir: '1988-06-06',
    gender: 'Laki Laki',
    alamat: 'Jl Mangga No.20',
    agama: 'Islam',
    pekerjaan: 'Wiraswasta',
    status: 'Active',
  },
  {
    id: '21',
    nama: 'Citra Dewi',
    namaPanggilan: 'Citra',
    tanggalLahir: '2001-01-01',
    gender: 'Perempuan',
    alamat: 'Jl Duku No.21',
    agama: 'Islam',
    pekerjaan: 'Barista',
    status: 'Inactive',
  },
  {
    id: '22',
    nama: 'Imam Ridwan',
    namaPanggilan: 'Imam',
    tanggalLahir: '1986-08-08',
    gender: 'Laki Laki',
    alamat: 'Jl Sawo No.22',
    agama: 'Islam',
    pekerjaan: 'Marketing',
    status: 'Active',
  },
  {
    id: '23',
    nama: 'Nadya Rahma',
    namaPanggilan: 'Nadya',
    tanggalLahir: '1995-04-04',
    gender: 'Perempuan',
    alamat: 'Jl Nangka No.23',
    agama: 'Kristen',
    pekerjaan: 'Admin',
    status: 'Active',
  },
  {
    id: '24',
    nama: 'Rizky Fadillah',
    namaPanggilan: 'Rizky',
    tanggalLahir: '1993-11-11',
    gender: 'Laki Laki',
    alamat: 'Jl Pepaya No.24',
    agama: 'Islam',
    pekerjaan: 'Karyawan',
    status: 'Inactive',
  },
  {
    id: '25',
    nama: 'Sari Ningsih',
    namaPanggilan: 'Sari',
    tanggalLahir: '1992-12-12',
    gender: 'Perempuan',
    alamat: 'Jl Durian No.25',
    agama: 'Islam',
    pekerjaan: 'Ibu Rumah Tangga',
    status: 'Active',
  },
]


export async function getPasienList(): Promise<Pasien[]> {
  return dummyData
}

export async function tambahPasien(pasienBaru: Omit<Pasien, 'id'>): Promise<Pasien> {
  const newPasien: Pasien = {
    ...pasienBaru,
    id: Date.now().toString(),
  }
  // dummyData.push(newPasien)
  return newPasien
}

export async function updatePasien(data: Pasien): Promise<void> {
  dummyData = dummyData.map((p) => (p.id === data.id ? data : p))
}

export async function deletePasien(id: string): Promise<void> {
  dummyData = dummyData.filter((p) => p.id !== id)
}
