'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";

import { useState } from 'react'
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { usePathname } from 'next/navigation';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [isOpen, setIsOpen] = useState(false)
  const toggleSidebar = () => setIsOpen(!isOpen)

  const pathname = usePathname();
  const isAuthPage = pathname === '/login' || pathname === '/home';

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen overflow-hidden`}>
        {isAuthPage ? (
          // Hanya render konten (tanpa Header/Sidebar)
          <ClientLayout>
            <div className="flex-1 flex flex-col">
              {children}
            </div>
          </ClientLayout>
        ) : (
          <ClientLayout>
            <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar} />
            <div className="flex-1 flex flex-col">
              <Header isOpen={isOpen} toggleSidebar={toggleSidebar} />
              {children}
            </div>
          </ClientLayout>
        )}
      </body>
    </html>
  );
}
